modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/RobertSkalko/Infinite-Dungeons/issues"
[[mods]]
modId="infinite_dungeons"
version="${file.jarVersion}"
displayName="Infinite Dungeons"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://www.curseforge.com/minecraft/mc-mods/infinite-dungeons"
logoFile="icon.png"
credits=""
authors="mcrobertx22"
description='''
Random quest mod themed around gods.
'''
[[dependencies.infinite_dungeons]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinite_dungeons]]
    modId="library_of_exile"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinite_dungeons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
