modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"
[[mods]]
modId="infinite_dungeons"
version="${file.jarVersion}"
displayName="Infinite Dungeons"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="icon.png"
credits=""
authors="mcrobertx22"
description='''
Random quest mod themed around gods.
'''
[[dependencies.infinite_dungeons]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinite_dungeons]]
    modId="library_of_exile"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinite_dungeons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
